data:
  root_dir: hest_data
  max_spots: 200

model:
  num_genes: 2000
  num_classes: 2
  embed_dim: 256
  fusion_option: attn
  top_k_genes: 512
  # Ablation options!!!!
  use_image: false
  use_st: true

training:
  epochs: 10
  lr: 0.0005
  weight_decay: 0.0001
  batch_size: 1

memory:
  batch_spots: 500
  accum_steps: 4
  freeze_image_encoder: true

misc:
  device: cuda
  seed: 42
  checkpoint_freq: 5